name: Coverage

on:
  workflow_run:
    workflows: [ "Linux" ]
    types: [ completed ]

jobs:
  upload:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download coverage build artifact
        uses: actions/download-artifact@v2
        with:
          name: coverage-build-artifact

      - uses: actions/setup-python@v2.2.1

      - name: Upload coverage to Coveralls
        run: |
          pip install cpp-coveralls
          coveralls --gcov-options '\-lp' -t ${{ secrets.COVERALLS_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
