name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-10.15 ] # macos-11.0
        build_type: [ Debug, Release ]
    env:
      CACHE_KEY_PREFIX: ${{ matrix.os }}-${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Install required libraries
        run: brew install libgit2 boost libarchive

      - name: Restore & Cache CMake build results
        uses: actions/cache@v2.1.3
        with:
          path: build
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ hashFiles('CMakeLists.txt', 'cmake/*.cmake') }}

      - run: mkdir -p build

      - name: Build Poac
        run: cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} .. && make
        working-directory: build

      - name: Test Poac
        run: ctest --output-on-failure --verbose
        working-directory: build

      - name: Print help
        run: ./poac help
        working-directory: build
